const fs = require("fs");
const path = require("path");

const projectRoot = path.resolve(__dirname, "..");
const packageJsonPath = path.join(projectRoot, "package.json");
const outputPath = path.join(projectRoot, "src", "generated", "version.ts");
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
const version = String(packageJson.version || "").trim();

if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(`Invalid package version: '${version}'`);
}

const output = [
  "// Generated from package.json by scripts/generate-version.js.",
  "// Do not edit this file directly.",
  `export const VERSION = ${JSON.stringify(version)};`,
  "",
].join("\n");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== output) {
  fs.writeFileSync(outputPath, output, "utf8");
}

console.log(`Generated x_Autopost version ${version}.`);
